// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyw8AEkuPEReKzP9OKp2xfJqV-T-YaItw',
    appId: '1:7642374609:web:79f3a48a7d1e41772000f0',
    messagingSenderId: '7642374609',
    projectId: 'malabarcampus-b36a8',
    authDomain: 'malabarcampus-b36a8.firebaseapp.com',
    storageBucket: 'malabarcampus-b36a8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsEi04ySnZEmk71Pu7uQx8A39lNbB215E',
    appId: '1:7642374609:android:1776df6ed2a531292000f0',
    messagingSenderId: '7642374609',
    projectId: 'malabarcampus-b36a8',
    storageBucket: 'malabarcampus-b36a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1Bb_xCcu1t8g6UEHzWeLbvI4F5CT7NPU',
    appId: '1:7642374609:ios:d1fd2dcef16dd7ff2000f0',
    messagingSenderId: '7642374609',
    projectId: 'malabarcampus-b36a8',
    storageBucket: 'malabarcampus-b36a8.firebasestorage.app',
    iosBundleId: 'com.example.helloWorld',
  );
}
